import type { Metadata } from "next";
import { Oxygen_Mono, Oxygen } from "next/font/google";
import "./globals.css";


const geistSans = Oxygen({
  subsets: ["latin"],
  weight:["300" , "400" ,"700" ],
  variable: "--font-oxygen-sans",
});

const geistMono = Oxygen_Mono({
  subsets: ["latin"],
  weight:["400"],
  variable: "--font-oxygen-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
        
      </body>
    </html>
  );
}
